Bugfix pgn mainline
benini/scid pull request #124
Opened 2023-05-29 13:58 UTC by ukscid

the pgn window was not updated after changing the option for a bold main line

2023-05-29 19:06 UTC, benini requested changes

2023-05-29 19:06 UTC, benini commented on tcl/windows/pgn.tcl
> +      if { $::pgn::boldMainLine } {
I do not want to reset the font every time that ::pgn::Refresh is executed.

2023-05-29 19:06 UTC, benini commented on tcl/windows/pgn.tcl
> +        -variable ::pgn::boldMainLine -command {::pgn::Refresh 1}
Probably just invoking configure with the right font should work and invoking ::pgn::Refresh may non be necessary.

2023-06-08 14:17 UTC, ukscid commented
update boldMainline by "text configure". Thanks for advice

2023-06-09 09:33 UTC, merged