Bugfix for resize board after a button is pressed
benini/scid pull request #125
Opened 2023-05-29 14:00 UTC by ukscid

After a button was pressed the keys "-" and "+" does not work. Fixed with this change

2023-05-29 19:03 UTC, benini requested changes

2023-05-29 19:03 UTC, benini commented on tcl/windows/browser.tcl
> +    set w .gb$n
I understand that the other gbrowser::functions do this, but resetting the window name in every function is wrong.

2023-05-29 19:03 UTC, benini commented on tcl/windows/browser.tcl
> -  bind $w <minus> {set ::gbrowser::size [::board::resize %W.bd -1]}
I think that something like:
`"set ::gbrowser::size \[::board::resize $w.bd -1 \]"`
should work and avoid adding another function that accepts a parameter `n`

2023-06-08 14:20 UTC, ukscid commented
Thanks for advice. updated in this way

2023-06-09 09:37 UTC, merged